module.exports = {
    PORT:  process.env.PORT || 3001,
    LINKEDIN_CLIENT_SECRET: process.env.LINKEDIN_CLIENT_SECRET,
    LINKEDIN_CLIENT_ID: process.env.LINKEDIN_CLIENT_ID,
    LINKEDIN_CALLBACK_URL: process.env.LINKEDIN_CALLBACK_URL
}