name: Aniline AI Backend Test - Deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: gitleaks-action
        uses: gitleaks/gitleaks-action@v1.6.0

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - name: npm install
        run: npm install
      - name: Create admin-sdk-key.json file
        run: echo "${ADMIN_SDK_KEY}" > admin-sdk-key.json
        env:
         ADMIN_SDK_KEY: ${{ secrets.ADMIN_SDK_KEY_DEV }}

      - name: Create firebase-config.json file
        run: echo "${FIREBASE_CONFIG}" > firebase-config.json
        env:
          FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG_DEV }}

      - name: Create .env file
        run: echo "${DEV_ENV}" > .env
        env:
          DEV_ENV: ${{ secrets.DEV_ENV }}

      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCLOUD_AUTH_DEV }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Configure Docker to use gcloud command-line tool
        run: |
          gcloud auth configure-docker

      - name: Build and push the container image
        run: |
          docker build -t "gcr.io/worksmi/worksmi-back-dev:${{ github.sha }}" ./
          docker push "gcr.io/worksmi/worksmi-back-dev:${{ github.sha }}"

      - name: Folders
        run: ls

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v0
        with:
          service: worksmi-back-dev
          region: us-central1
          image: gcr.io/worksmi/worksmi-back-dev:${{ github.sha }}
